export const jobInputs=[
    {
        id:1,
        label:"Id",
        type:"text",
        placeholder:"Id",
    },
    {
        id:1,
        label:"Company",
        type:"text",
        placeholder:"Company name",
    },
    {
        id:2,
        label:"role",
        type:"text",
        placeholder:"Role"
    },
    {
        id:3,
        label:"location",
        type:"text",
        placeholder:"location"
    },
    {
        id:4,
        label:"CTC",
        type:"text",
        placeholder:"CTC"
    },
    {
        id:5,
        label:"type",
        type:"text",
        placeholder:"type"
    },
    {
        id:6,
        label:"Experiance",
        type:"text",
        placeholder:"Experiance"
    },
    {
        id:7,
        label:"Branch",
        type:"text",
        placeholder:"Branch"
    },
    {
        id:8,
        label:"Percentage",
        type:"number",
        placeholder:"Percentage"
    },
    {
        id:9,
        label:"CGPA",
        type:"number",
        placeholder:"CGPA"
    },
    {
        id:10,
        label:"Backlog",
        type:"number",
        placeholder:"Backlog"
    },
    {
        id:11,
        label:"Note",
        type:"text",
        placeholder:"Note"
    },
    {
        id:12,
        label:"About_job",
        type:"text",
        placeholder:"Job description"
    },
    {
        id:13,
        label:"About_Company",
        type:"text",
        placeholder:"Company description"
    },
    {
        id:14,
        label:"Requirments",
        type:"text",
        placeholder:"Requirments"
    },
    {
        id:15,
        label:"last_date",
        type:"datetime-local",
        placeholder:"last date"
    },
]

export const announcementInput=[
    {
        id:1,
        label:"Id",
        type:"text",
        placeholder:"Id",
    },
    {
        id:1,
        label:"title",
        type:"text",
        placeholder:"title"
    },
    {
        id:2,
        label:"subject",
        type:"text",
        placeholder:"subject"
    },
    {
        id:3,
        label:"location",
        type:"text",
        placeholder:"location"
    },
    {
        id:4,
        label:"date",
        type:"date",
        placeholder:"date"
    },
    {
        id:5,
        label:"time",
        type:"time",
        placeholder:"time"
    },
]