export const codingData = [
    {
        slno:1,
        icon: 'figma',
        label: 'Part 1 | Introduction To Programming | C Programming Malayalam Tutorial',
        videoId:'pDmEYRhyusU',
        duration: '42 min',
        type:"Video",
    },
    {
        slno:2,
        icon: 'twitch',
        label: 'Linux Installation | Eclipse IDE',
        videoId:'XW7HI6ajZfo',
        duration: '8 min',
        type:"Video",
    },
    {
        slno:3,
        icon: 'github',
        label: 'Windows Installation | Eclipse IDE',
        videoId:'Kyt8gJGFEn4',
        duration: '12 min',
        type:"Video",
    },
    {
        slno:4,
        icon: 'gitlab',
        label: 'Mac Installation | Eclipse IDE ',
        videoId:'ZVhSZGkAM2E',
        duration: '9 min',
        type:"Video",
    },
    {
        slno:5,
        icon: 'twitter',
        label: 'Part 2 | Variables Datatypes & I/O Operations',
        videoId:'qGGqnzvKjmM',
        duration: '1 hr 4 min',
        type:"Video",
    },
    {
        slno:6,
        icon: 'codesandbox',
        label: 'Part 3 | Conditional Statements IF, IF ELSE, SWITCH',
        videoId:'W7s0upNfcKY',
        duration: '48 min',
        type:"Video",
    },
    {
        slno:7,
        icon: 'codepen',
        label: 'Part 4 | Loops: FOR Loop ',
        videoId:'YfaJzXFbFcQ',
        duration: '1 hr 3 min',
        type:"Video",
    },
    {
        slno:8,
        icon: 'dribbble',
        label: 'Part 5 | Array and Array Operations',
        videoId:'d0drJeqmiws',
        duration: '1 hr 28 min',
        type:"Video",
    },
    {
        slno:9,
        icon: 'dribbble',
        label: 'Part 6 | Functions and Type of Functions',
        videoId:'lFgyEWxNI58',
        duration: '1 hr 28 min',
        type:"Video",
    },
    {
        slno:10,
        icon: 'dribbble',
        label: 'Part 7 | OOP Concepts: Class and Objects | Java Programming Malayalam Tutorial',
        videoId:'G1FahZ5Sgik',
        duration: '1 hr 29 min',
        type:"Video",
    },
    {
        slno:11,
        icon: 'dribbble',
        label: 'Part 8 | Constructors, Inheritance, Polymorphism',
        videoId:'MxuTGyBz9BA',
        duration: '1 hr 25 min',
        type:"Video",
    },
    {
        slno:12,
        icon: 'dribbble',
        label: 'Part 9 | Abstract Class, Exceptions, Threads',
        videoId:'MRFD3Cnug1Q',
        duration: '1 hr 23 min',
        type:"Video",
    },
    {
        slno:13,
        icon: 'dribbble',
        label: 'Part 10 | Calculator Project From Scratch ',
        videoId:'AUxawaW4DAc',
        duration: '1 hr 32 min',
        type:"Video",
    },
    {
        slno:14,
        icon: 'figma',
        label: 'Coding Practice Set',
        duration: '60 pages',
        type:"PDF",
        pdfUrl:'https://media.licdn.com/dms/document/C4D1FAQGyvQw7bey9Dw/feedshare-document-pdf-analyzed/0/1670516376083?e=1683158400&v=beta&t=db3LWviUbAQm-YKVDfw07xa8hqt5niZ5S2mufTcp90M'
    },
    {
        slno:15,
        icon: 'figma',
        label: 'SQL',
        duration: '56 pages',
        type:"PDF",
        pdfUrl:'https://media.licdn.com/dms/document/C4D1FAQFrj4sl8lfu1A/feedshare-document-pdf-analyzed/0/1672900487252?e=1683158400&v=beta&t=YRF3iwjGqMBq4ptBd9yzj7G3VYTXOkRZWBRad4XtlZg'
    },
    {
        slno:16,
        icon: 'figma',
        label: 'SQL Solved Questions',
        duration: '21 pages',
        type:"PDF",
        pdfUrl:'https://media.licdn.com/dms/document/C561FAQGR0rtxDJTTRw/feedshare-document-pdf-analyzed/0/1674439527157?e=1683158400&v=beta&t=seyjVdm8oRRpt_bv2pykSPEqvBticdik1N6O_acIzXI'
    },
];


export const interviewData = [
    {
        slno:1,
        icon: 'figma',
        label: 'Tell Me Something About Yourself? | Introduce Yourself? | Interview Questions',
        videoId:'F4jahYCbDJA',
        duration: '21 min',
        type:"Video",
    },
    {
        slno:2,
        icon: 'twitch',
        label: 'Where do you see yourself in 5 Years? | Best Sample Answers for Freshers ',
        videoId:'bZKXrbcexBg',
        duration: '6 min',
        type:"Video",
    },
    {
        slno:3,
        icon: 'github',
        label: 'Why Should We Hire You?',
        videoId:'5VfWCawt-Q0',
        duration: '3 min',
        type:"Video",
    },
    {
        slno:4,
        icon: 'gitlab',
        label: 'Why Do You Want To Join Our Company? ',
        videoId:'LTCjAMOS5u8',
        duration: '10 min',
        type:"Video",
    },
    {
        slno:5,
        icon: 'twitter',
        label: 'How to Introduce Yourself in English',
        videoId:'oQceWPmGEOo',
        duration: '15 min',
        type:"Video",
    },
    {
        slno:6,
        icon: 'codesandbox',
        label: 'How to Crack an Interview From Introduction ? | How to Introduce Yourself Smartly',
        videoId:'xRzXCHT-jLs',
        duration: '21 min',
        type:"Video",
    },
    {
        slno:7,
        icon: 'figma',
        label: 'A Complete Guide for a Great Resume',
        duration: '11 pages',
        type:"PDF",
        pdfUrl:'https://media.licdn.com/dms/document/C4D1FAQGf0Xjq8ZPOXg/feedshare-document-pdf-analyzed/0/1672632170705?e=1683158400&v=beta&t=Y57F4uy_3MVDIRK08mGd4bZMWlXAL8HPCGMrPcmQ7AE'
    },
    {
        slno:8,
        icon: 'figma',
        label: 'Common Job Interview Questions and Answers Samples',
        duration: '14 pages',
        type:"PDF",
        pdfUrl:'https://media.licdn.com/dms/document/C561FAQGhWm_LPQ7aeA/feedshare-document-pdf-analyzed/0/1672410378644?e=1683158400&v=beta&t=vpZLH3Fjxqrr3FZtwAUNGosUpgvWhcoDgWD3F4WMvsY'
    },
];